autoCorrect: true
failFast: true

style:
  MaxLineLength:
    maxLineLength: 120
  UnusedPrivateMember:
    active: false
  WildcardImport:
    active: false
  UnnecessaryAbstractClass:
    active: false
  ForbiddenComment:
    active: false

comments:
  active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

complexity:
  LabeledExpression:
    active: false
  TooManyFunctions:
    active: false
  ComplexMethod:
    active: false

potential-bugs:
  UnsafeCast:
    active: false
  LateinitUsage:
    active: false
